### ISSUE TITLE
KiCad 3D rendered not looked like description

### ISSUE THREAD

**Issue by manobendro** [gregdavill/obsidian-boa#1]
What is the secret of kiCad 3d rendering? How to render like description image.

**Comment by gregdavill** [comment]
The rendering has been created in Autodesk Fusion360 using the `.STEP` output from the KiCad designs. When I have a prototype in hand I'll be replacing it with a photo.

Here is a talk walking through the process: https://www.youtube.com/watch?v=L25B5WaZ2EI

**Comment by manobendro** [comment]
Wow! It take lot of effort to look like realistic.
