### ISSUE TITLE
R7 and R8 on pcb layout

### ISSUE THREAD

**Issue by GlebDen** [gregdavill/obsidian-boa#7]
Hello again. 
I've noticed another odd thing.
On your scheme R7 = 453K and R8 = 100K. But on pcb this numbers are different - 180K both.
According to datasheet of TPS62290 Vout=Vref x (1+R1\R2)
(453\100+1) x 0.6 = 3.318V

**Comment by gregdavill** [comment]
Interesting, that probably just needs to be synced up.

453/100 appear to be the correct values
